package devops.om;


import org.apache.torque.om.Persistent;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Mon Mar 26 14:30:11 IST 2018]
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
public  class Table1
    extends devops.om.BaseTable1
    implements Persistent
{
    /** Serial version */
    private static final long serialVersionUID = 1522054811459L;

}
